#!/bin/bash
set -e

VERSION=$1
if [ -z "$VERSION" ]; then
  echo "Usage: $0 <version>"
  echo "Example: $0 0.3.6"
  exit 1
fi

echo "Downloading binaries for v$VERSION..."

# 下载所有平台的 tar.gz 包
mkdir -p /tmp/mcpx-downloads
cd /tmp/mcpx-downloads

curl -sL "https://github.com/AIGC-Hackers/mcpx/releases/download/v$VERSION/mcpx-darwin-arm64.tar.gz" -o mcpx-darwin-arm64.tar.gz
curl -sL "https://github.com/AIGC-Hackers/mcpx/releases/download/v$VERSION/mcpx-linux-arm64.tar.gz" -o mcpx-linux-arm64.tar.gz
curl -sL "https://github.com/AIGC-Hackers/mcpx/releases/download/v$VERSION/mcpx-linux-x64.tar.gz" -o mcpx-linux-x64.tar.gz

echo "Calculating SHA256 checksums..."

# 计算 SHA256
DARWIN_ARM64_SHA=$(shasum -a 256 mcpx-darwin-arm64.tar.gz | awk '{print $1}')
LINUX_ARM64_SHA=$(shasum -a 256 mcpx-linux-arm64.tar.gz | awk '{print $1}')
LINUX_X64_SHA=$(shasum -a 256 mcpx-linux-x64.tar.gz | awk '{print $1}')

echo "Darwin ARM64: $DARWIN_ARM64_SHA"
echo "Linux ARM64:  $LINUX_ARM64_SHA"
echo "Linux x64:    $LINUX_X64_SHA"

# 获取当前脚本所在目录
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 更新 formula
cat > "$SCRIPT_DIR/Formula/mcpx.rb" << EOF
# ⚠️  AUTO-GENERATED - DO NOT EDIT MANUALLY!
# This file is generated by CI. Manual edits will be overwritten.
# To update: See CLAUDE.md or trigger update-homebrew.yml workflow
class Mcpx < Formula
  desc "Extended TypeScript runtime and CLI for Model Context Protocol"
  homepage "https://github.com/AIGC-Hackers/mcpx"
  version "$VERSION"
  license "MIT"

  on_macos do
    url "https://github.com/AIGC-Hackers/mcpx/releases/download/v$VERSION/mcpx-darwin-arm64.tar.gz"
    sha256 "$DARWIN_ARM64_SHA"
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/AIGC-Hackers/mcpx/releases/download/v$VERSION/mcpx-linux-arm64.tar.gz"
      sha256 "$LINUX_ARM64_SHA"
    else
      url "https://github.com/AIGC-Hackers/mcpx/releases/download/v$VERSION/mcpx-linux-x64.tar.gz"
      sha256 "$LINUX_X64_SHA"
    end
  end

  def install
    bin.install "mcpx"
    zsh_completion.install "completions/_mcpx"
    bash_completion.install "completions/mcpx.bash" => "mcpx"
    fish_completion.install "completions/mcpx.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mcpx --version")
  end
end
EOF

echo "✅ Formula updated: $SCRIPT_DIR/Formula/mcpx.rb"
echo ""
echo "Next steps:"
echo "1. cd $SCRIPT_DIR"
echo "2. git add Formula/mcpx.rb"
echo "3. git commit -m 'chore: update to v$VERSION'"
echo "4. git push"

# 清理
cd ..
rm -rf /tmp/mcpx-downloads
