# ⚠️  AUTO-GENERATED - DO NOT EDIT MANUALLY!
# This file is generated by CI. Manual edits will be overwritten.
# To update: See CLAUDE.md or trigger update-homebrew.yml workflow
class Mcpx < Formula
  desc "Extended TypeScript runtime and CLI for Model Context Protocol"
  homepage "https://github.com/AIGC-Hackers/mcpx"
  version "0.6.0"
  license "MIT"

  on_macos do
    url "https://github.com/AIGC-Hackers/mcpx/releases/download/v0.6.0/mcpx-darwin-arm64"
    sha256 "d86405d6c224528ecff0b7163b26a763605e2fbe75f583941f1295e5669156a7"
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/AIGC-Hackers/mcpx/releases/download/v0.6.0/mcpx-linux-arm64"
      sha256 "f4f824f0b00b23d79ba1e2104d1dc3111ec5d2a44fccbff4b4469f319907b970"
    else
      url "https://github.com/AIGC-Hackers/mcpx/releases/download/v0.6.0/mcpx-linux-x64"
      sha256 "6a33f829c8582ba85b913e82b240dcb53a9d668c776fc1d5d07e25fa4c5b8741"
    end
  end

  def install
    bin.install Dir["*"].first => "mcpx"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mcpx --version")
  end
end
