# ⚠️  AUTO-GENERATED - DO NOT EDIT MANUALLY!
# This file is generated by CI. Manual edits will be overwritten.
# To update: See CLAUDE.md or trigger update-homebrew.yml workflow
class Mcpx < Formula
  desc "Extended TypeScript runtime and CLI for Model Context Protocol"
  homepage "https://github.com/AIGC-Hackers/mcpx"
  version "0.7.0"
  license "MIT"

  on_macos do
    url "https://github.com/AIGC-Hackers/mcpx/releases/download/v0.7.0/mcpx-darwin-arm64"
    sha256 "ac5dc8648dfd0b390f559f8f8e40b1959debd759fe17cf3ba3ae7825133e70fd"
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/AIGC-Hackers/mcpx/releases/download/v0.7.0/mcpx-linux-arm64"
      sha256 "7fa57f68389d11e9730130c3eab84be561261fde8c876f12787b67f1d5dcea90"
    else
      url "https://github.com/AIGC-Hackers/mcpx/releases/download/v0.7.0/mcpx-linux-x64"
      sha256 "0dac68854d4333e9bf5644d29e0837b216516a37ae94245fbf04e6943bd364ea"
    end
  end

  resource "zsh-completion" do
    url "https://raw.githubusercontent.com/AIGC-Hackers/mcpx/v0.7.0/completions/_mcpx"
    sha256 "b9c1102919165d7552a9b0f9f3b0d3f7e17359c6ba2bf345cb20e0380bf1e2ac"
  end

  resource "bash-completion" do
    url "https://raw.githubusercontent.com/AIGC-Hackers/mcpx/v0.7.0/completions/mcpx.bash"
    sha256 "ecbad2f2c5e3ce98b68b6dcab360e86bf822fbb4c874e3e04a4801794c7db758"
  end

  resource "fish-completion" do
    url "https://raw.githubusercontent.com/AIGC-Hackers/mcpx/v0.7.0/completions/mcpx.fish"
    sha256 "87016a7851870b1e2569ae439a3c4925110405ce94bd5752a4725963c70f1fd4"
  end

  def install
    bin.install Dir["mcpx-*"].first => "mcpx"

    # Install shell completions
    resource("zsh-completion").stage { zsh_completion.install "_mcpx" }
    resource("bash-completion").stage { bash_completion.install "mcpx.bash" => "mcpx" }
    resource("fish-completion").stage { fish_completion.install "mcpx.fish" }
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mcpx --version")
  end
end
